/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AOI: typeof import('./src/components/AOI.vue')['default']
    BBTAVI: typeof import('./src/components/BBTAVI.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    Drilling: typeof import('./src/components/Drilling.vue')['default']
    DroughtPrevention: typeof import('./src/components/DroughtPrevention.vue')['default']
    ECharts: typeof import('./src/components/ECharts.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElectroPlating: typeof import('./src/components/ElectroPlating.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    JiangXiN2: typeof import('./src/components/JiangXiN2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
